# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sn_dGO3XxuMWPGhVVfni82ic8vdyra0L
"""

pip install torch torchvision

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
import numpy as np

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))  # MNIST mean and std
])

train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset  = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

def split_forget_retain(dataset, forget_classes: list):
    forget_indices = [i for i, (_, label) in enumerate(dataset) if label in forget_classes]
    retain_indices = [i for i, (_, label) in enumerate(dataset) if label not in forget_classes]

    forget_set = Subset(dataset, forget_indices)
    retain_set = Subset(dataset, retain_indices)
    return forget_set, retain_set

forget_classes = [2, 7]  # example: forget digits 2 and 7
forget_set, retain_set = split_forget_retain(train_dataset, forget_classes)

train_loader  = DataLoader(train_dataset, batch_size=64, shuffle=True,  num_workers=2)
test_loader   = DataLoader(test_dataset,  batch_size=64, shuffle=False, num_workers=2)
forget_loader = DataLoader(forget_set,    batch_size=64, shuffle=True,  num_workers=2)
retain_loader = DataLoader(retain_set,    batch_size=64, shuffle=True,  num_workers=2)

import matplotlib.pyplot as plt

def show_samples(dataset, title, n=10):
    fig, axes = plt.subplots(1, n, figsize=(15, 2))
    fig.suptitle(title)
    for i, ax in enumerate(axes):
        image, label = dataset[i]
        ax.imshow(image.squeeze(), cmap='gray')
        ax.set_title(str(label))
        ax.axis('off')
    plt.tight_layout()
    plt.savefig(f'{title.replace(" ", "_")}.png')
    plt.show()

show_samples(train_dataset, 'All training samples')
show_samples(forget_set,    'Forget set')
show_samples(retain_set,    'Retain set')